//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public int JournalID { get; set; }
        public int DebitAccountNumber { get; set; }
        public int CreditAccountNumber { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
    }
}
